// frontend/react/src/components/modal.jsx
import { useEffect, useState } from 'react';
import XIcon from './x-icon';

function Modal({ open, onClose, defaultName, onSave }) {
  const [name, setName] = useState(defaultName);

  useEffect(() => {
    if (defaultName && defaultName !== name) {
      setName(defaultName);
    }
  }, [defaultName]);

  if (!open) {
    return null;
  }

  return (
    <div className="mask">
      <div className="modal">
        <form className="form">
          <button type="button" onClick={onClose} className="btn-close">
            <XIcon />
          </button>
          <div className="input-group">
            <label htmlFor="name" className="label">
              Task's name
            </label>
            <input
              id="name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="input"
            />
          </div>
          <button
            type="button"
            onClick={() => {
              onSave(name);
              onClose();
              setName(null);
            }}
            className="btn-save"
          >
            Save
          </button>
        </form>
      </div>
    </div>
  );
}

export default Modal;

// frontend/vue/src/components/modal.vue
<script setup>
import XIcon from './x-icon.vue';
import { ref, watch } from 'vue';

const name = ref(null);

const props = defineProps({
  open: Boolean,
  onClose: Function,
  defaultName: String,
  onSave: Function,
});

watch(
  () => props.defaultName,
  (value) => {
    if (value && value !== name.value) {
      name.value = value;
    }
  }
);
</script>
<template>
  <div v-if="open" class="mask">
    <div class="modal">
      <form class="form">
        <button type="button" @click="$emit('onClose')" class="btn-close">
          <XIcon />
        </button>
        <div class="input-group">
          <label htmlFor="name" class="label">Task's name</label>
          <input
            id="name"
            :value="name"
            @input="(event) => (name = event.target.value)"
            class="input"
          />
        </div>
        <button
          type="button"
          @click="
            () => {
              $emit('onSave', name);
              $emit('onClose');
              name = null;
            }
          "
          class="btn-save"
        >
          Save
        </button>
      </form>
    </div>
  </div>
</template>
