// frontend/vue/src/components/task.vue
<script setup>
import EditIcon from './edit-icon.vue';
import TrashIcon from './trash-icon.vue';

defineProps({
  name: String,
  onUpdate: Function,
  onDelete: Promise,
});
</script>

<template>
  <article class="task">
    <div class="name">{{ name }}</div>
    <div class="actions">
      <button @click="$emit('onUpdate')" class="btn-edit">
        <EditIcon />
      </button>
      <button @click="$emit('onDelete')" class="btn-delete">
        <TrashIcon />
      </button>
    </div>
  </article>
</template>

// frontend/react/src/components/task.jsx
import EditIcon from './edit-icon';
import TrashIcon from './trash-icon';

function Task({ name, onUpdate, onDelete }) {
  return (
    <article className="task">
      <div className="name">{name}</div>
      <div className="actions">
        <button onClick={onUpdate} className="btn-edit">
          <EditIcon />
        </button>
        <button onClick={onDelete} className="btn-delete">
          <TrashIcon />
        </button>
      </div>
    </article>
  );
}

export default Task;
