// frontend/vue/src/app.vue
<script setup>
import { ref, onBeforeMount } from 'vue';
import Task from './components/task.vue';
import Modal from './components/modal.vue';
import * as api from './api/rest';

const open = ref(false);
const tasks = ref([]);
const selectedTask = ref(null);

onBeforeMount(() => {
  api.findAllTaks().then((data) => (tasks.value = data));
});

async function onCreate(name) {
  const task = await api.createTask({ name });
  tasks.value = [...tasks.value, { id: task.id, name: task.name }];
}

async function onUpdate(name) {
  await api.updateTaskById(selectedTask.value.id, { name });
  tasks.value = tasks.value.map((task) =>
    task.id === selectedTask.value.id ? { ...task, name } : task
  );
  selectedTask.value = null;
}

async function onDelete(id) {
  await api.deleteTaskById(id);
  tasks.value = tasks.value.filter((task) => task.id !== id);
}

function onSave(name) {
  if (selectedTask.value) {
    onUpdate(name);
  } else {
    onCreate(name);
  }
}
</script>

<template>
  <div class="card">
    <div class="header">
      <div class="logo">TODO</div>
      <div class="count">{{ tasks.length }} tasks</div>
    </div>
    <div class="body">
      <Task
        v-for="task in tasks"
        :name="task.name"
        @on-update="
          () => {
            selectedTask = task;
            open = true;
          }
        "
        @on-delete="() => onDelete(task.id)"
      />
    </div>
    <button @click="open = true" class="btn-add">Add task</button>
  </div>
  <Modal
    :open="open"
    :default-name="selectedTask?.name"
    @on-close="open = false"
    @on-save="onSave"
  />
</template>

// frontend/react/src/app.jsx
import { useState, useEffect } from 'react';
import Task from './components/task';
import Modal from './components/modal';
import * as api from './api/rest';

function App() {
  const [open, setOpen] = useState(false);
  const [tasks, setTasks] = useState([]);
  const [selectedTask, setSelectedTask] = useState(null);

  useEffect(() => {
    api.findAllTaks().then((data) => setTasks(data));
  }, []);

  async function onCreate(name) {
    const task = await api.createTask({ name });
    const newTasks = [...tasks, { id: task.id, name: task.name }];
    setTasks(newTasks);
  }

  async function onUpdate(name) {
    await api.updateTaskById(selectedTask.id, { name });
    const newTasks = tasks.map((task) => (task.id === selectedTask.id ? { ...task, name } : task));
    setTasks(newTasks);
    setSelectedTask(null);
  }

  async function onDelete(id) {
    await api.deleteTaskById(id);
    const newTasks = tasks.filter((task) => task.id !== id);
    setTasks(newTasks);
  }

  function onSave(name) {
    if (selectedTask) {
      onUpdate(name);
    } else {
      onCreate(name);
    }
  }

  return (
    <>
      <div className="card">
        <div className="header">
          <div className="logo">TODO</div>
          <div className="count">{tasks.length} tasks</div>
        </div>
        <div className="body">
          {tasks.map((task) => (
            <Task
              key={task.id}
              name={task.name}
              onUpdate={() => {
                setSelectedTask(task);
                setOpen(true);
              }}
              onDelete={() => onDelete(task.id)}
            />
          ))}
        </div>
        <button onClick={() => setOpen(true)} className="btn-add">
          Add task
        </button>
      </div>

      <Modal
        defaultName={selectedTask?.name}
        open={open}
        onClose={() => setOpen(false)}
        onSave={onSave}
      />
    </>
  );
}

export default App;
